### ISSUE TITLE
should organizers be able to delete a bus they made?

### ISSUE THREAD

**Issue by duncangraham** [hivemindworks/Argo-Project-V0#100]
If an organizer can delete a bus, what's the reasoning?

If a bus gets made, and is full of people that have made reservations and the organizer deletes it, what happens?

I would say lets remove the ability for organizers to delete buses for the time being.

**Comment by freindst** [comment]
I agree with your consideration. I just think there should be a function that organizer can cancel a trip if there is something wrong, such as schedule conflicts
One thing is only allow organizer delete a trip before organizer approved it (no one can pledge before organizer inserting a template)
Another thing is move it to organizer side. If there is some reason the trip has to be canceled (maybe snow storm?), organizer will contact with everyone in the trip.

**Comment by markstm17** [comment]
![11868624_10154098915257598_139006615_n](https://cloud.githubusercontent.com/assets/11848699/9178463/faac536e-3f5c-11e5-8a27-6969e5b9677a.jpg)


@duncangraham there could be a lot of reasonings. I think we need to have the organizer have the ability to do this, but say there is a $50 cancellation policy or something. We discourage it because our system makes it easier for people to know what the cost was, currently is and could be based upon the number of people signed up. 

For now we DON'T need the feature/ability, but I think we should have ability in the future. (Especially if we are focusing on private trips to begin with)


Thoughts @duncangraham and @freindst ??

**Comment by duncangraham** [comment]
what we have right now isn't really "private". Anyone can buy a reservation, as long as they have a link. 

If we choose to make a true 'private' execution then I think canceling a bus should be an option associated with a fee potentially. For public buses, if a bus has been given the green light (enough people to pay for it) then the organizer shouldn't be able to cancel it.

**Comment by freindst** [comment]
I have made edit/delete button no-clickable after admin added a template. Besides, add message that user need to contact with admin, and then admin shall help user and have further actions. 
Private and Public trip discussion will be continuing in #107.
