### ISSUE TITLE
Encrypting Real Credit Card Info when we switch from Fake to Real

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#19]
Cyber Security behind the identity of future customers is vital

**Comment by freindst** [comment]
For credit card, we are using Braintree for payment. We do not store credit card. User will submit credit card information to Braintree, and after Braintree verifies payment validation, a payment confidential token will be granted to user. Instead of using credit card directly, we store such token as payment authentication evidence. I agree that cyber security is the most important fact in business, and definitely all payment related information needs to be encrypted and kept secured.

**Comment by mlitman** [comment]
Credit card info is stored in BrainTree’s vault, which is specifically built for this exact purpose.  I would say the credit card info is secure in the current scenario.

Mike

Dr. Michael Litman, PhD
Co-Owner
Director of Software Development
Out of the Box Apps
http://www.awesomefat.com <http://www.awesomefat.com/>
awesomefat@ootbapps.com
cell: 262-353-6205

**Comment by markstm17** [comment]
Sounds great. Thanks @mlitman and @freindst

**Comment by freindst** [comment]
Duplicated of #110
