### ISSUE TITLE
app crashes when I tried to add a payment method

### ISSUE THREAD

**Issue by duncangraham** [hivemindworks/Argo-Project-V0#81]
browser
--
<img width="1392" alt="screen shot 2015-08-04 at 10 47 00 pm" src="https://cloud.githubusercontent.com/assets/865298/9079067/ce0f0132-3afa-11e5-9223-a2d89c0eba72.png">

terminal
--
<img width="1389" alt="screen shot 2015-08-04 at 10 47 07 pm" src="https://cloud.githubusercontent.com/assets/865298/9079068/ce0fe43a-3afa-11e5-99dc-87b6ff42e5b0.png">

tried to add the card '4111 1111 1111 1111' expiration date 05/19

any ideas @freindst?

**Comment by freindst** [comment]
It says, cannot read"template.template_nodes", so the reason is the trip has not linked to a template.
I guess you have chosen this trip:
![screen shot 2015-08-05 at 8 17 34 am](https://cloud.githubusercontent.com/assets/13219475/9086579/ce567ec2-3b4a-11e5-93ed-9b4b2e11e4a3.png)
This is something I need to improve, hide trip without template.

**Comment by freindst** [comment]
I have settled it. So it can be closed.
