### ISSUE TITLE
Create Trip Page Edits 8/5/2015

### ISSUE THREAD

**Issue by markstm17** [hivemindworks/Argo-Project-V0#88]
Check out the comment on #76 @duncangraham

**Comment by duncangraham** [comment]
what is this ticket? I don't understand the purpose or what you're trying to communicate @markstm17

**Comment by markstm17** [comment]
@duncangraham Just reopened it for you and @freindst to check out and understand


If it is confusing or you still don't get it we can talk. And ultimately I know enough about how the process works where we can adjust the pricing. Not a big deal, but I'm just trying to communicate the process through my experience

**Comment by freindst** [comment]
I feel the same as @duncangraham . I also cannot understand there is any value to open a new issue and discuss the same problem. We will keep on go through all issues until it has been closed. There is no need to open a same one in order to catch our attention. I am closing it and merging to #76.
duplicate #76
